#! /bin/sh
### BEGIN INIT INFO
# Provides:          site
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: site
# Description:       ADA
### END INIT INFO
#
# Author:      WTI
#


set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/home/ricardopaschoali/siteinfo
SL_PATH=/home/ricardopaschoali/siteinfo
DAEMON="/home/ricardopaschoali/siteinfo/siteInfo.py "
PIDFILE=/var/run/site.pid

test -x $SL_PATH || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting deferred execution siteInfo"
	start_daemon -p $PIDFILE $DAEMON
	#sudo $DAEMON
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution siteInfo"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/siteInfo {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
